---
title: "Einführung in AutoCAD für Archäologen"
author: Christoph Rinne
email: crinne@ufg.uni-kiel.de
date: "`r format(Sys.time(), '%d. %B %Y')`"
license: "CC-BY-NC 4.0"
header-includes:
  \renewcommand{\contentsname}{Inhalt}
  \renewcommand{\figurename}{Abb.}
bibliography: AutoCAD-cours-references.bib
csl: journal-of-archaeological-science.csl
output:
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
    df_print: kable
  html_document:
    toc: yes
    toc_float: true
    df_print: paged
papersize: a4 
urlcolor: blue
link-citations: yes # make citations hyperlinks
linkcolor: blue
# number_sections: yes
lang: de-DE
---

# Text und Textstile

Dieses Thema wurde im Kapitel 4 "Editieren ..." und im vorangehenden bei "Block mit Attribut" angerissen. Die Bedeutung von Textstilen bzw. Formatvorlagen erschließt sich von selbst und muss nicht erläutert werden. Es gibt aber einige wenige wichtige Aspekte, die zu beachten sind und gesondert erwähnt werden sollen.

- In AutoCAD stehen zwei Gruppen von Schrifttypen zur Verfügung: 
	- SHX, die AutoCAD eigenen, auf Vektoren basierten Schriften und
	- TTF (True Type Font) oder andere Schriftarten des Betriebssystems.
- Sofern nicht Standardfonts des Betriebssystem (OS) verwendet werden, müssen TTF im darstellenden OS vorliegen oder im PDF eingebunden sein, ansonsten werden diese automatisch durch einen anderen Font ersetzt,  fehlerhaft oder auch gar nicht dargestellt. Bis 2021 gab es die PDF Standard Type 1 Fonts (u.a. Times, Courier, Helvetica). PDF/A(rchiv) schreibt das Einbinden der Fonts vor, was allerdings durch die Anwendung zur PDF-Erstellung auch unterstützt werden muss. Eine fehlerhafte Darstellung erfolgt auch in der AutoCAD-Datei selbst, wenn der verwendetet Font im neuen OS nicht vorliegt.  
- Text lässt sich in AutoCAD, unabhängig ob SHX oder TTF, vorliegt "Suchen" und "Ersetzen". Beim Druck in eine PDF-Datei wird SHX zu Vektoren umgewandelt während TTF *a priori* zu Text wird. Die Verwendung von TTF bietet für die automatisierte Recherche und die Extraktion von Inhaltsinformationen im resultierende PDF also immense Vorteile. 
- Da SHX zu Vektoren umgewandelt werden bleibt der Text im PDF unabhängig vom OS menschenlesbar. In Abhängigkeit von der Menge des Textes und der Proportion zu weiteren Vektoren nimmt die Dateigröße aber unverhältnismäßig zu.
- Veränderungen bei TTF von Breitenfaktor, Neigung oder Rotation sowie die uneinheitliche Skalierung von x und y bei einem Block mit Text können die Konvertierung des Textes im PDF verhindern oder zu fehlerhafter Darstellung führen.
- Sie können in AutoCAD mehrere Textstile definieren und diese gezielt nach Bedarf und mit Blick auf interoperable und durchsuchbare PDF einsetzen. Sie sollten nur einen und möglichst weit verbreiteten Font verwenden.
